name: ci

on:
  push:
    tags: [ 'v*.*.*' ]

jobs:
  docker-build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Extract package version
        run: node -p -e '`PACKAGE_VERSION=${require("./package.json").version}`' >> $GITHUB_ENV
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
        with:
          platforms: linux/amd64,linux/arm64,linux/arm/v7
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build and push to GitHub Container Registry
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./Dockerfile
          platforms: linux/amd64,linux/arm/v7,linux/arm64
          push: true
          tags: |
            ghcr.io/${{ github.repository }}:${{ env.PACKAGE_VERSION }},
            ghcr.io/${{ github.repository }}:latest

  ha-addon-build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        arch: [amd64, aarch64, armv7]
        include:
          - arch: amd64
            platform: linux/amd64
            base: homeassistant/amd64-base:latest
          - arch: aarch64
            platform: linux/arm64/v8
            base: homeassistant/aarch64-base:latest
          - arch: armv7
            platform: linux/arm/v7
            base: homeassistant/armv7-base:latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Extract package version
        run: node -p -e '`PACKAGE_VERSION=${require("./package.json").version}`' >> $GITHUB_ENV
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
        with:
          platforms: ${{ matrix.platform }}
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build and push HA Addon
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./Dockerfile.HA_ADDON
          build-args: BUILD_FROM=${{ matrix.base }}
          platforms: ${{ matrix.platform }}
          push: true
          tags: |
            ghcr.io/${{ github.repository }}-ha-addon-${{ matrix.arch }}:${{ env.PACKAGE_VERSION }},
            ghcr.io/${{ github.repository }}-ha-addon-${{ matrix.arch }}:latest
